### NUMPY

In [1]:
import numpy 

In [2]:
stu_roll = numpy.array([10,11,12,13,14,15,16,17,18])
print(stu_roll)
print(stu_roll.dtype)

[10 11 12 13 14 15 16 17 18]
int32


In [3]:
stu_roll.ndim

1

In [4]:
stu_roll.size

9

In [5]:
stu_roll.shape

(9,)

### View
This is used to construct a new view of array with the same data of existing array

In [6]:
stu_roll = numpy.array([10,11,12,13,14,15])
acc = stu_roll.view()

print(stu_roll)
print(acc)

print()
print(id(stu_roll))
print(id(acc))

[10 11 12 13 14 15]
[10 11 12 13 14 15]

2487204896368
2487204894256


In [7]:
stu_roll[1]

11

In [8]:
stu_roll = numpy.array([10,11,12,13,14,15], dtype= float)
print(stu_roll)

[10. 11. 12. 13. 14. 15.]


In [9]:
stu_roll = numpy.array(["yash","yogesh","aman","sharad"])
print(stu_roll)

['yash' 'yogesh' 'aman' 'sharad']


In [10]:
from numpy import *
stu_roll = array(["yash",101,102,103.55,True])
print(stu_roll)

['yash' '101' '102' '103.55' 'True']


### For Loop accessing array

In [11]:
roll = array([10,20,"aman","sharad",40,50])

for element in roll:
    
    print(element)

10
20
aman
sharad
40
50


In [12]:
roll = array([10,20,"aman","sharad",40,50])

n =len(roll)
for i in range(n):
    print("index",i,"-",roll[i])

index 0 - 10
index 1 - 20
index 2 - aman
index 3 - sharad
index 4 - 40
index 5 - 50


In [13]:
roll = array([10,20,"aman","sharad",40,50])
n=len(roll)
i=0
while i<n:
    print("index",i,"-",roll[i])
    i+=1

index 0 - 10
index 1 - 20
index 2 - aman
index 3 - sharad
index 4 - 40
index 5 - 50


### Linspace () function  
This is used to create an array with evenly spaced numbers between a start point and stop point

In [14]:
from array import *

In [15]:
a = linspace(1,8)
print(a)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.         3.14285714 3.28571429 3.42857143
 3.57142857 3.71428571 3.85714286 4.         4.14285714 4.28571429
 4.42857143 4.57142857 4.71428571 4.85714286 5.         5.14285714
 5.28571429 5.42857143 5.57142857 5.71428571 5.85714286 6.
 6.14285714 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286
 7.         7.14285714 7.28571429 7.42857143 7.57142857 7.71428571
 7.85714286 8.        ]


In [16]:
a = linspace(1,8,5, endpoint = False)
print(a)

[1.  2.4 3.8 5.2 6.6]


In [17]:
print(a[2])

3.8


### logspace() function
This is used to create an array with evenly spaced numbers logrithmically

In [18]:
a = logspace(1,8)
print(a)

[1.00000000e+01 1.38949549e+01 1.93069773e+01 2.68269580e+01
 3.72759372e+01 5.17947468e+01 7.19685673e+01 1.00000000e+02
 1.38949549e+02 1.93069773e+02 2.68269580e+02 3.72759372e+02
 5.17947468e+02 7.19685673e+02 1.00000000e+03 1.38949549e+03
 1.93069773e+03 2.68269580e+03 3.72759372e+03 5.17947468e+03
 7.19685673e+03 1.00000000e+04 1.38949549e+04 1.93069773e+04
 2.68269580e+04 3.72759372e+04 5.17947468e+04 7.19685673e+04
 1.00000000e+05 1.38949549e+05 1.93069773e+05 2.68269580e+05
 3.72759372e+05 5.17947468e+05 7.19685673e+05 1.00000000e+06
 1.38949549e+06 1.93069773e+06 2.68269580e+06 3.72759372e+06
 5.17947468e+06 7.19685673e+06 1.00000000e+07 1.38949549e+07
 1.93069773e+07 2.68269580e+07 3.72759372e+07 5.17947468e+07
 7.19685673e+07 1.00000000e+08]


In [19]:
a = logspace(1,8,5)
print(a)

[1.00000000e+01 5.62341325e+02 3.16227766e+04 1.77827941e+06
 1.00000000e+08]


### arange function()  
 arange function is used to create an array with a group of elements 

In [20]:
b = arange(5)
print(b)

[0 1 2 3 4]


In [21]:
b = arange(1,10,2)
print(b)

[1 3 5 7 9]


### initializing different types of array

### zeros function()
zeros function is used to create an array will all zeros

In [22]:
b = zeros(8)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
b = zeros(8, dtype=complex)
print(b)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [24]:
b = zeros((4,2))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### ones function () 
ones function is used to create an array with all 1s

In [25]:
b = ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [26]:
b = ones((3,4,6))
print(b)

[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]


In [27]:
#Any other number
import numpy as np
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [28]:
# Repeat of array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### input by user

In [29]:
user = int(input("enter the number of element:"))
ab = ones(n ,dtype = int)

print(ab)

enter the number of element:5
[1 1 1 1 1 1]


In [30]:
import numpy as np
tst = np.array([[1,2,3,4],
              [5,6,7,8]])

print(tst)
print(type(tst))
print(tst.dtype)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
int32


In [31]:
print(tst[0][2])

3


In [32]:
print(tst[1][3])

8


In [33]:
tst = np.array([ [1,2,3,4],
                [5,6,7,8] ])

for i in tst:
    for c in i:
        print(c)
    print()

1
2
3
4

5
6
7
8



In [34]:
tst = np.array([ [1,2,3,4],
                [5,6,7,8] ])
n=len(tst)
i=0
while i<n:
    print("index",i,"-",tst[i])
    i+=1

index 0 - [1 2 3 4]
index 1 - [5 6 7 8]


### convert 1-D To 2-D array


In [35]:
from numpy import *

In [36]:
arry = array([1,2,3,4,5,6,7,8,9,10,11,12])
shp = reshape(arry,(3,4))

print(arry)
print()
print(shp)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### convert 2-D To 1-D

In [37]:
arry = array([[1,2,3,4],[5,6,7,8]])
shp = reshape(arry,(8))

print(arry)
print()
print(shp)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]


### convert 1-D To 3-D

In [38]:
arry = array([1,2,3,4,5,6,7,8,9,10,11,12])
shp = reshape(arry,(2,3,2))

print(arry)
print()
print(shp)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
arry = array([[10,20,30],
             [40,50,60],
             [70,80,90]])

print(arry)
print(type(arry))

[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>


In [40]:
arry[:]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [41]:
arry[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [42]:
print("0 th row all column")
arry[0,:]

0 th row all column


array([10, 20, 30])

In [43]:
print("2nd row all column")
arry[2,:]

2nd row all column


array([70, 80, 90])

In [44]:
print("0 th row all column")
arry[:,0]

0 th row all column


array([10, 40, 70])

In [45]:
arry[0:1,0:1]

array([[10]])

In [46]:
arry[2:3,0:1]

array([[70]])

In [47]:
arry[2:3,2:3]

array([[90]])

In [48]:
arry[0:2,1:3]

array([[20, 30],
       [50, 60]])

### numpy .random .rand()
this function creates an array of specified shape and fills it with random values

In [49]:
np.random.rand(40)

array([0.98509633, 0.94217135, 0.25857827, 0.40727579, 0.96274941,
       0.32485304, 0.593768  , 0.46033884, 0.60192519, 0.27533488,
       0.48367681, 0.73154092, 0.13346368, 0.83648208, 0.83414016,
       0.80651682, 0.46535924, 0.34707008, 0.20217275, 0.92281416,
       0.47062546, 0.36269707, 0.11599555, 0.97706767, 0.78937886,
       0.46219209, 0.61943206, 0.13984863, 0.47461946, 0.74254854,
       0.10106701, 0.59561965, 0.10217722, 0.85507943, 0.7544818 ,
       0.39680479, 0.33907102, 0.82337782, 0.26244331, 0.42345884])

### numpy .random .randn()
this function creates an array of specified shape and fills it with random values as per standard normal distribution

In [50]:
np.random.randn(20)

array([ 0.43608356, -0.68172006, -0.88078679,  0.50388908,  0.06749655,
       -0.77412006, -0.78297697,  0.66496344, -0.17152532,  0.11576423,
        1.02291864,  0.50716857, -0.38272634,  0.57889463,  0.74443044,
        0.29831974, -0.48342554,  0.06985074,  1.94841615,  2.20905085])

###  numpy .random .randint()
It returns an array of specified shape and fills it with random intergers form low to higher limits

In [51]:
np.random .randint(6)

4

In [52]:
np.random.randint(5,40,(4,4))

array([[19, 10, 30, 16],
       [16, 15, 28, 18],
       [14, 15, 10, 13],
       [17, 12, 15, 32]])

In [53]:
np.random.randint(3,9,(3,3))

array([[6, 5, 5],
       [4, 7, 4],
       [4, 5, 5]])

### Matrix 

In [54]:
var = np.matrix([[1,3,4],[1,2,6]])

print(var)
print(type(var))
print()

print(np.transpose(var))

[[1 3 4]
 [1 2 6]]
<class 'numpy.matrix'>

[[1 1]
 [3 2]
 [4 6]]


In [55]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [56]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])